CREATE TABLE IF NOT EXISTS phone (id BIGINT AUTO_INCREMENT PRIMARY KEY, model VARCHAR(255) NOT NULL, is_available BOOLEAN NOT NULL, version INT NOT NULL);

CREATE TABLE IF NOT EXISTS booking (id BIGINT AUTO_INCREMENT PRIMARY KEY, booked_by VARCHAR(255) NOT NULL, booked_at TIMESTAMP NOT NULL, phone_id BIGINT,
    CONSTRAINT fk_phone FOREIGN KEY(phone_id) REFERENCES phone(id));
